version: '3.3'

services:

  web:
    build: ./engbook
    command: gunicorn engbook.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./engbook/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    env_file:
      - ./engbook/.env
    depends_on:
      - db
      

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./engbook/.env.db


  nginx:
    build: ./webserver
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:      

  
## OLD 


# version: "3.7"

# services:


#   django:
#     build: ./engbook
#     container_name: backend
#     restart: always
#     volumes: 
#       - ./engbook/static/:/bkserver/static
#     environment: 
#       - APP_NAME=LogbookBackend
#     expose:
#       - 8080
  
#   nginx:
#     build: ./webserver
#     container_name: webserver-nginx
#     restart: always
#     volumes: 
#       - ./engbook/static/:/staticroot
#     ports: 
#       - "80:80"
