# Generated by Django 3.0.5 on 2020-05-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logfile',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logger',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
