# Generated by Django 3.0.5 on 2020-05-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20200516_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='note',
            field=models.TextField(),
        ),
    ]
