# Generated by Django 3.0.5 on 2020-05-17 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0002_auto_20200516_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logfile',
            name='slug',
            field=models.SlugField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='logger',
            name='slug',
            field=models.SlugField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='logger',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=127)),
                ('slug', models.SlugField(max_length=127, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('note', models.TextField(max_length=1023)),
                ('date_modified', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
