# Generated by Django 3.0.5 on 2020-05-17 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200517_1854'),
        ('log', '0004_auto_20200517_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='logger',
            name='isNote',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='logger',
            name='private',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='logger',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project.Project'),
        ),
    ]
