# Generated by Django 3.0.5 on 2020-05-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='techskill',
            field=models.ManyToManyField(blank=True, null=True, to='user.TechSkill'),
        ),
    ]
