# Generated by Django 3.0.5 on 2020-05-16 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200516_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='log',
            new_name='profile',
        ),
    ]
