# Generated by Django 3.0.5 on 2020-05-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200516_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
