# Generated by Django 3.0.5 on 2020-05-19 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200516_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='field_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.FieldStudy'),
        ),
    ]
