name: Pull Request CI

on:
  pull_request:
    branches: [ master ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Set up Environment
      run: |
        cp engbook/.env.example engbook/.env
        export KEY=`uuidgen`
        sed "s/YOUR SECRET_KEY/$KEY/g" engbook/.env -i
        sed "s/DEBUG=/DEBUG=False/g" engbook/.env -i
    - name: Install Dependencies
      run: |
        python -m pip install wheel
        python -m pip install --upgrade pip
        pip install -r engbook/requirements.txt
    - name: Run Tests
      run: |
        cd engbook
        python manage.py test
