# Generated by Django 3.0.5 on 2020-05-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200516_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(max_length=127, null=True),
        ),
    ]
